#!/bin/sh -ex

. /usr/share/ganeti/extstorage/zfs/defaults.sh

log_start $*

# lvrename ffzgvg cc9b16d9-7d14-452a-9150-74521bd8e721.disk0 d275c91f-70a7-4270-972c-b020fde9580b.disk0_data

if [ "$EXTP_VG" = "$1" ] ; then

	zfs rename $EXTP_ZFS/$2 $EXTP_ZFS/$3

	if [ $? -eq 0 ]; then

		# symbolic links also need to be adapted in /dev/$EXTP_VG
		if ! echo $3 | grep -q "replaced" ; then
			dev=`readlink --canonicalize /dev/$EXTP_VG/$2`
			log_event "Adding symbolic link from /dev/$EXTP_VG/$3 to $dev"
			ln -svf $dev /dev/$EXTP_VG/$3 >&2

			# delete old link only if the new link succeeded
			if [ $? -eq 0 ]; then
				log_event "Deleting old link /dev/$EXTP_VG/$2"
				rm -f /dev/$EXTP_VG/$2
			fi
		fi

# commented out as this is this is not useful here
		# rename filesystems with snapshots using clone/promote
#		zfs snap  $EXTP_ZFS/$2@$3
#		zfs clone $EXTP_ZFS/$2@$3 $EXTP_ZFS/$3
#		zfs promote $EXTP_ZFS/$3  # new zvol is now origin
#		zfs destroy -R $EXTP_ZFS/$3@$3

	fi

else
	/sbin/lvm lvrename $*
fi
